version: "3.8"

services:
  dbmongo:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  myos:
    depends_on:
      - dbmongo
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "4000:4000"
    environment:
      - DB_URL=$DB_URL
    stdin_open: true
    tty: true
volumes:
  db: